### ISSUE TITLE
getting Phone number from Magento contact us form 

### ISSUE THREAD

**Issue by elnile** [CopeX/magento-osticket-api#1]
Hi there first I would thank you for this extension, it's working fine but I just noticed that after a client submit a phone number as on my contact form, it wont show up on the osticket, and when checking the "System Logs" on the osticket side it's showing "API Unexpected Data"

**Comment by roman204** [comment]
Hy MHusien,
osticket does normally not "allow" all data to be transferred via the "API". We transfer as much as possible data as [here](https://github.com/CopeX/magento-osticket-api/blob/master/app/code/community/CopeX/OSTicketAPI/Model/Observer.php#L34) defined
